# Generated by Django 5.1.1 on 2024-09-25 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.TextField()),
                ('Ingredients', models.TextField()),
                ('Instructions', models.TextField(blank=True, null=True)),
                ('Category', models.CharField(choices=[('Desert', 'Desert'), ('Main Course', 'Main Course')], max_length=100)),
                ('Preparation_Time', models.PositiveIntegerField()),
                ('Cooking_ime', models.PositiveIntegerField()),
                ('Servings', models.PositiveIntegerField()),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
