# Generated by Django 5.1.1 on 2024-09-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Category',
            field=models.CharField(choices=[('Desert', 'Desert'), ('Main Course', 'Main Course'), ('Breakfast', 'Breakfast'), ('vegertrian', 'vegetrian'), ('appetizer', 'Appetizer'), ('drink', 'Drink')], max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Cooking_ime',
            field=models.PositiveIntegerField(help_text='Cooking time in minutes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Preparation_Time',
            field=models.PositiveIntegerField(help_text='Preparation time in minutes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Servings',
            field=models.PositiveIntegerField(),
        ),
    ]
