# Generated by Django 5.1.1 on 2024-09-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_category_alter_recipe_cooking_ime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Cooking_ime',
            new_name='Cooking_Time',
        ),
    ]
